{"ast":null,"code":"var _jsxFileName = \"/Users/arpansahu/projects/profile/altered_datum/src/components/ErrorBoundary.js\";\nimport React, { Component } from 'react';\n\nclass ErrorBoundary extends Component {\n  constructor(props) {\n    super(props);\n    this.state = {\n      hasError: false\n    };\n  }\n\n  static getDerivedStateFromError(error) {\n    // Update state so the next render will show the fallback UI.\n    return {\n      hasError: true\n    };\n  }\n\n  componentDidCatch(error, errorInfo) {\n    // Log the error to an error reporting service\n    // logErrorToMyService(error, errorInfo);\n    console.error(\"ErrorBoundary caught an error\", error, errorInfo);\n  }\n\n  render() {\n    if (this.state.hasError) {\n      // You can render any custom fallback UI\n      return /*#__PURE__*/React.createElement(\"div\", {\n        style: {\n          padding: '20px',\n          textAlign: 'center'\n        },\n        __self: this,\n        __source: {\n          fileName: _jsxFileName,\n          lineNumber: 24,\n          columnNumber: 17\n        }\n      }, /*#__PURE__*/React.createElement(\"h1\", {\n        __self: this,\n        __source: {\n          fileName: _jsxFileName,\n          lineNumber: 25,\n          columnNumber: 21\n        }\n      }, \"Something went wrong.\"), /*#__PURE__*/React.createElement(\"p\", {\n        __self: this,\n        __source: {\n          fileName: _jsxFileName,\n          lineNumber: 26,\n          columnNumber: 21\n        }\n      }, \"We're sorry for the inconvenience. The error has been logged and we'll look into it.\"), /*#__PURE__*/React.createElement(\"button\", {\n        onClick: () => window.location.reload(),\n        __self: this,\n        __source: {\n          fileName: _jsxFileName,\n          lineNumber: 27,\n          columnNumber: 21\n        }\n      }, \"Try Again\"), /*#__PURE__*/React.createElement(\"br\", {\n        __self: this,\n        __source: {\n          fileName: _jsxFileName,\n          lineNumber: 28,\n          columnNumber: 21\n        }\n      }), /*#__PURE__*/React.createElement(\"a\", {\n        href: \"/\",\n        __self: this,\n        __source: {\n          fileName: _jsxFileName,\n          lineNumber: 29,\n          columnNumber: 21\n        }\n      }, \"Go to Homepage\"));\n    }\n\n    return this.props.children;\n  }\n\n}\n\nexport default ErrorBoundary;","map":{"version":3,"sources":["/Users/arpansahu/projects/profile/altered_datum/src/components/ErrorBoundary.js"],"names":["React","Component","ErrorBoundary","constructor","props","state","hasError","getDerivedStateFromError","error","componentDidCatch","errorInfo","console","render","padding","textAlign","window","location","reload","children"],"mappings":";AAAA,OAAOA,KAAP,IAAgBC,SAAhB,QAAiC,OAAjC;;AAEA,MAAMC,aAAN,SAA4BD,SAA5B,CAAsC;AAClCE,EAAAA,WAAW,CAACC,KAAD,EAAQ;AACf,UAAMA,KAAN;AACA,SAAKC,KAAL,GAAa;AAAEC,MAAAA,QAAQ,EAAE;AAAZ,KAAb;AACH;;AAED,SAAOC,wBAAP,CAAgCC,KAAhC,EAAuC;AACnC;AACA,WAAO;AAAEF,MAAAA,QAAQ,EAAE;AAAZ,KAAP;AACH;;AAEDG,EAAAA,iBAAiB,CAACD,KAAD,EAAQE,SAAR,EAAmB;AAChC;AACA;AACAC,IAAAA,OAAO,CAACH,KAAR,CAAc,+BAAd,EAA+CA,KAA/C,EAAsDE,SAAtD;AACH;;AAEDE,EAAAA,MAAM,GAAG;AACL,QAAI,KAAKP,KAAL,CAAWC,QAAf,EAAyB;AACrB;AACA,0BACI;AAAK,QAAA,KAAK,EAAE;AAAEO,UAAAA,OAAO,EAAE,MAAX;AAAmBC,UAAAA,SAAS,EAAE;AAA9B,SAAZ;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,sBACI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,iCADJ,eAEI;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,gGAFJ,eAGI;AAAQ,QAAA,OAAO,EAAE,MAAMC,MAAM,CAACC,QAAP,CAAgBC,MAAhB,EAAvB;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,qBAHJ,eAII;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,QAJJ,eAKI;AAAG,QAAA,IAAI,EAAC,GAAR;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA;AAAA,0BALJ,CADJ;AASH;;AAED,WAAO,KAAKb,KAAL,CAAWc,QAAlB;AACH;;AAhCiC;;AAmCtC,eAAehB,aAAf","sourcesContent":["import React, { Component } from 'react';\n\nclass ErrorBoundary extends Component {\n    constructor(props) {\n        super(props);\n        this.state = { hasError: false };\n    }\n\n    static getDerivedStateFromError(error) {\n        // Update state so the next render will show the fallback UI.\n        return { hasError: true };\n    }\n\n    componentDidCatch(error, errorInfo) {\n        // Log the error to an error reporting service\n        // logErrorToMyService(error, errorInfo);\n        console.error(\"ErrorBoundary caught an error\", error, errorInfo);\n    }\n\n    render() {\n        if (this.state.hasError) {\n            // You can render any custom fallback UI\n            return (\n                <div style={{ padding: '20px', textAlign: 'center' }}>\n                    <h1>Something went wrong.</h1>\n                    <p>We're sorry for the inconvenience. The error has been logged and we'll look into it.</p>\n                    <button onClick={() => window.location.reload()}>Try Again</button>\n                    <br />\n                    <a href=\"/\">Go to Homepage</a>\n                </div>\n            );\n        }\n\n        return this.props.children; \n    }\n}\n\nexport default ErrorBoundary;"]},"metadata":{},"sourceType":"module"}